### ISSUE TITLE
Unpermitted parameter: webpay_tokenと出ます

### ISSUE THREAD

**Issue by mitsunobuk** [webpay/webpay_closet#11]
既存のrailsのアプリにwebpayを組み込めるか試しております。

定期購入をしたいので、webpay_closetを参考に作っているのですが、アカウント編集にてカード情報を入力し、updateしてもlogには「Unpermitted parameter: webpay_token」となり、上手く動きません。dbのusersにwebpay_customer_idを追加しております。

config/routes.rb
`devise_for :users, controllers: { registrations: 'users/registrations' }`

app/controllers/users/registrations_controller.rb
`class Users::RegistrationsController < Devise::RegistrationsController
  def create
    self.resource = user = User.new(sign_up_params)
    if user.save
      sign_up(:user, user)
      begin
        user.update_webpay_customer_id
        notice = [:signed_up]
        location = after_sign_up_path_for(user)
      rescue WebPay::ApiError => e
        notice = ['signed_up_but_webpay_error', message: e.data.error.message]
        location = edit_user_registration_path
      end
      set_flash_message :notice, *notice if is_flashing_format?
      respond_with user, :location => location
    else
      clean_up_passwords user
      respond_with user
    end
  end
  def update
    self.resource = user = current_user
    if user.update_with_password(account_update_params)
      sign_in :user, user, :bypass => true
      begin
        user.update_webpay_customer_id
        notice = [:updated]
        location = after_update_path_for(user)
      rescue WebPay::ApiError => e
        notice = ['updated_but_webpay_error', message: e.data.error.message]
        location = edit_user_registration_path
      end
      set_flash_message :notice, *notice if is_flashing_format?
      respond_with user, :location => location
    else
      clean_up_passwords user
      respond_with user
    end
  end
end`

app/models/users.rb
`class User < ActiveRecord::Base
  class NoWebPayAccountError < RuntimeError
  end
  include WebPayClient
  attr_accessor :webpay_token
  def update_webpay_customer_id
    return if self.webpay_customer_id.nil? && webpay_token.blank?
    if self.webpay_customer_id
      req = { id: self.webpay_customer_id }
      req[:card] = self.webpay_token if webpay_token.present?
      req[:email] = self.email if self.email
      req[:description] = self.name if self.name
      webpay.customer.update(req)
    else
      created = webpay.customer.create(card: webpay_token, email: self.email, description: self.name)
      update_attributes(webpay_customer_id: created.id)
    end
  end
  def webpay_customer
    @webpay_customer ||= webpay.customer.retrieve(webpay_customer_id) if webpay_customer_id
  end
  def webpay_customer_id_or_raise
    self.webpay_customer_id.presence or raise NoWebPayAccountError.new
  end
end`
を追加しております。もし何かお分かりになる事がありましたら教えていただければと思います。よろしくお願いいたします。

**Comment by hmsk** [comment]
開発中の環境では Strong Parameters が機能しているために permit を通さずに webpay_token というパラメータを呼び出しているために発生しているエラーではないかと存じます。
https://github.com/rails/strong_parameters

webpay_closetでは`webpay_token`はDeviseの範疇にあるパラメータであるため、指定されている処理を[application_controller](https://github.com/webpay/webpay_closet/blob/master/app/controllers/application_controller.rb)で行っています。
https://github.com/plataformatec/devise#strong-parameters
